name: Test, build and deploy
on: [push]
env:
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
  CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  API_ME_TOKEN: ${{secrets.API_ME_TOKEN}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: yarn install
    - name: Lint
      run: yarn lint
    - name: Unit Test
      run: yarn test:ci
    - name: Build
      run: yarn build
    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: ./docs
    - name: Deploy Package
      run: npx semantic-release